# Generated by Django 5.1.1 on 2025-01-15 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='hobby_description',
        ),
    ]
